name: CI
on: [push]
jobs:
  build:
    name: Build, lint, and test on Node ${{ matrix.node }} and ${{ matrix.os }}

    runs-on: ${{ matrix.os }}
    strategy:
     matrix:
      os: [ubuntu-latest, windows-latest, macOS-latest]
      node: [14.x, 16.x, 18.x]
      exclude:
      - os: macOS-latest
        node: 10.x
      - os: macOS-latest
        node: 12.x
      - os: macOS-latest
        node: 14.x
      - os: macOS-latest
        node: 16.x
      - os: macOS-latest
        node: 18.x

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Install deps and build (with cache)
        uses: bahmutov/npm-install@v1

      - name: Lint
        run: yarn lint

      - name: Test
        run: yarn test --ci --coverage --maxWorkers=2

      - name: Build
        run: yarn build
